### ISSUE TITLE
Add Pre-Commit Config Yaml

### ISSUE THREAD

**Issue by Skylion007** [scivision/linkchecker-markdown#20]
Request to add a .pre-commit-hooks.yaml file to allow it to be used with the pre-commit python git hook management framework: https://github.com/pre-commit/pre-commit/

**Comment by shivan-s** [comment]
I'd love this feature. I've added it in as a local hook.

```yaml
  - repo: local
    hooks:
    - id: linkchecker-markdown
      name: linkchecker-markdown
      entry: linkchecker-markdown
      language: system
      types: [python]
```

But the problem I've had is that it doesn't check the files. So will need to do more investigation.
